<?php

namespace Application\ApplicationBundle\Repository;

/**
 * CustdataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustdataRepository extends \Doctrine\ORM\EntityRepository
{
}
