app_application_product:
    resource: "@AppApplicationBundle/Resources/config/routing/product.yml"
    prefix:   /product
app_application_default:
    resource: "@AppApplicationBundle/Resources/config/routing/default.yml"
    prefix:   /default        
app_application_sales:
    resource: "@AppApplicationBundle/Resources/config/routing/sales.yml"
    prefix:   /sales

app_application_user:
    resource: "@AppApplicationBundle/Resources/config/routing/user.yml"
    prefix:   /user
app_application_transaction:
    resource: "@AppApplicationBundle/Resources/config/routing/transaction.yml"
    prefix:   /transaction
app_application_customer:
    resource: "@AppApplicationBundle/Resources/config/routing/customer.yml"
    prefix:   /customer