Application\ApplicationBundle\Entity\Customer:
    type: entity
    table: null
    repositoryClass: Application\ApplicationBundle\Repository\CustomerRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        customerId:
            type: string
            length: '255'
        customerName:
            type: string
            length: '255'
        customerPoints:
            type: string
            length: '255'
        customerEmail:
            type: string
            length: '255'
        customerPassword:
            type: string
            length: '255'
        customerBirthdate:
            type: datetime
        customerJoinDate:
            type: datetime
        
    lifecycleCallbacks: {  }
