Application\ApplicationBundle\Entity\User:
    type: entity
    table: null
    repositoryClass: Application\ApplicationBundle\Repository\UserRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        username:
            type: string
            length: '255'
        password:
            type: string
            length: '255'
            unique: true
    lifecycleCallbacks: {  }
