customer_index:
    path:     /
    defaults: { _controller: "AppApplicationBundle:Customer:index" }
    methods:  GET

customer_show:
    path:     /{id}/show
    defaults: { _controller: "AppApplicationBundle:Customer:show" }
    methods:  GET

customer_new:
    path:     /new
    defaults: { _controller: "AppApplicationBundle:Customer:new" }
    methods:  [GET, POST]

customer_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppApplicationBundle:Customer:edit" }
    methods:  [GET, POST]

customer_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppApplicationBundle:Customer:delete" }
    methods:  DELETE
customer_completePurchase:
    path:     /completePurchase
    defaults: { _controller: "AppApplicationBundle:Customer:completePurchase" }
    methods:  [GET]
user_login:
    path:     /login
    defaults: { _controller: "AppApplicationBundle:Customer:login" }
    methods:  GET