product_index:
    path:     /
    defaults: { _controller: "AppApplicationBundle:Product:index" }
    methods:  GET

product_index_new:
    path:     /new
    defaults: { _controller: "AppApplicationBundle:Product:indexNew" }
    methods:  GET
    
product_show:
    path:     /{id}/show
    defaults: { _controller: "AppApplicationBundle:Product:show" }
    methods:  GET
    
product_productList:
    path:     /productList
    defaults: { _controller: "AppApplicationBundle:Product:productList" }
    methods:  GET
    
product_new:
    path:     /new
    defaults: { _controller: "AppApplicationBundle:Product:new" }
    methods:  [GET, POST]

product_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppApplicationBundle:Product:edit" }
    methods:  [GET, POST]

product_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppApplicationBundle:Product:delete" }
    methods:  DELETE



login_form:
    path:     /login
    defaults: { _controller: "AppApplicationBundle:Security:login" }
    methods:  [GET, POST]
product_addProductToCart:
    path:     /addProductToCart
    defaults: { _controller: "AppApplicationBundle:Product:addProductToCart" }
    methods:  [GET]
product_exportDataProduct:
    path:     /exportDataProduct
    defaults: { _controller: "AppApplicationBundle:Product:exportDataProduct", _format: xlsx }
    methods:  [GET]

product_add_newjs:
    path:     /addNewProductJS
    defaults: { _controller: "AppApplicationBundle:Product:addNewProductJS" }
    methods:  [GET, POST]
product_edit_form_newjs:
    path:     /editFormNewProductJS
    defaults: { _controller: "AppApplicationBundle:Product:editFormNewProductJS" }
    methods:  [GET, POST]
product_edit_submit_form_newjs:
    path:     /editSubmitFormProductJs
    defaults: { _controller: "AppApplicationBundle:Product:editSubmitFormProductJs" }
    methods:  [GET, POST]
product_delete_submit_form_newjs:
    path:     /deleteProductJs
    defaults: { _controller: "AppApplicationBundle:Product:deleteProductJs" }
    methods:  [GET, POST]