sales_index:
    path:     /
    defaults: { _controller: "AppApplicationBundle:Sales:index" }
    methods:  GET
sales_newindex:
    path:     /new
    defaults: { _controller: "AppApplicationBundle:Sales:newIndex" }
    methods:  GET

sales_show:
    path:     /{id}/show
    defaults: { _controller: "AppApplicationBundle:Sales:show" }
    methods:  GET

sales_new:
    path:     /new
    defaults: { _controller: "AppApplicationBundle:Sales:new" }
    methods:  [GET, POST]

sales_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppApplicationBundle:Sales:edit" }
    methods:  [GET, POST]

sales_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppApplicationBundle:Sales:delete" }
    methods:  DELETE
    
sales_showListSalesByDateRange:
    path:     /showListSalesByDateRange
    defaults: { _controller: "AppApplicationBundle:Sales:showListSalesByDateRange" }
    methods:  GET

seles_indexSalesNewJs:
    path:     /indexSalesNewJs
    defaults: { _controller: "AppApplicationBundle:Sales:indexSalesNewJs" }
    methods:  GET
seles_editSalesNewJs:
    path:     /editSalesNewJs
    defaults: { _controller: "AppApplicationBundle:Sales:editSalesNewJs" }
    methods:  GET
sales_editSalesTemplateNewJs:
    path: / editSalesTemplateNewJs
    defaults: {_controller: "AppApplicationBundle:Sales:editSalesTemplateNewJs"}
    methods:  GET